name: Unit testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing GTK
      run: sudo apt install libgtk-3-dev
    - name: Compile all + unit testing
      run: make
    - name: Cleaning the repository
      run: make clean
    
